### PR TITLE
Bump copyright year in readme.md

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR bumps the copyright year in the README.md file.

Happy new year! 🎉

### Note

This PR should only be merged once a change to any content of this repository was done.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@dreske Please merge this PR!

**Comment by Ein-Tim** [comment]
@larswmh Please merge this PR!

**Comment by larswmh** [comment]
@Ein-Tim I unfortunately don't have permissions for this repository.

**Comment by Ein-Tim** [comment]
@dreske Could you please press "Merge"? Thanks!

**Comment by Ein-Tim** [comment]
@dsarkar Could you bring this PR to @dreske's or someones attention, who has the rights to merge it, please?

**Comment by Ein-Tim** [comment]
cc @GisoSchroederSAP Would be great to get this PR merged!

**Pull request closed without merging**
